version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    image: node:21-alpine3.17
    ports:
      - "3001:3001"
    volumes:
      - ./db.json:/opt/db.json
    working_dir: /opt
    command: sh -c "yarn global add json-server@0.17.4 && json-server -H 0.0.0.0 -p 3001 /opt/db.json"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
