version: "3.8"

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    image: node:20-alpine
    ports:
      - "3001:3001"
    volumes:
      - ./db.json:/opt/db.json
    working_dir: /opt
    command: sh -c "yarn global add json-server@0.17.4 && json-server -H 0.0.0.0 -p 3001 /opt/db.json"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
